# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default.global.parameters]
stack_name = "tax-app-backend"
region = "us-east-1"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "tax-app-backend-dev"
parameter_overrides = "Environment=\"production\" CorsAllowedOrigin=\"https://tax-app-git-dev-ryaml1221-ryan.vercel.app\" FromEmail=\"taxapp67@gmail.com\""
image_repositories = []
stack_name = "tax-app-backend-dev"

[production.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "tax-app-backend-prod"
parameter_overrides = "Environment=\"production\" CorsAllowedOrigin=\"https://the-tax-app.vercel.app\" FromEmail=\"taxapp67@gmail.com\""
image_repositories = []
stack_name = "tax-app-backend"

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
