"""
Property-based tests for email validation in the login endpoint.

These tests verify universal properties across randomized inputs using hypothesis.
Each property test runs with a minimum of 100 iterations.
"""

import pytest
from hypothesis import given, settings, strategies as st
from hypothesis.strategies import emails
from user_login.validator import ValidationError, validate_email


class TestEmailValidationProperty:
    """Property-based tests for email validation."""
    
    @settings(max_examples=20)
    @given(email=emails())
    def test_valid_emails_are_accepted(self, email):
        """
        **Validates: Requirements 2.1, 2.2**
        Feature: user-login-endpoint, Property 2: Email validation
        
        For any valid RFC 5322 format email, the validator should accept it.
        """
        # Valid emails generated by hypothesis should be accepted
        assert validate_email(email) is True
    
    @settings(max_examples=20)
    @given(
        invalid_email=st.one_of(
            # Email without @ symbol
            st.text(alphabet=st.characters(blacklist_characters='@'), min_size=1, max_size=50),
            # Just @ symbol
            st.just("@"),
            # @ at the start
            st.builds(lambda domain: f"@{domain}", domain=st.text(min_size=1, max_size=20)),
            # @ at the end
            st.builds(lambda local: f"{local}@", local=st.text(min_size=1, max_size=20)),
            # Multiple @ symbols
            st.builds(lambda a, b, c: f"{a}@{b}@{c}", 
                     a=st.text(min_size=1, max_size=10),
                     b=st.text(min_size=1, max_size=10),
                     c=st.text(min_size=1, max_size=10)),
            # Empty string
            st.just(""),
            # Whitespace only
            st.text(alphabet=" \t\n", min_size=1, max_size=10),
            # No domain after @
            st.builds(lambda local: f"{local}@", 
                     local=st.text(alphabet=st.characters(blacklist_characters='@'), 
                                  min_size=1, max_size=20)),
            # Invalid characters in domain
            st.builds(lambda local, domain: f"{local}@{domain}", 
                     local=st.text(alphabet=st.characters(blacklist_characters='@'), 
                                  min_size=1, max_size=20),
                     domain=st.text(alphabet="!#$%&*", min_size=1, max_size=10)),
        )
    )
    def test_invalid_emails_are_rejected(self, invalid_email):
        """
        **Validates: Requirements 2.1, 2.2**
        Feature: user-login-endpoint, Property 2: Email validation
        
        For any invalid email format, the validator should reject it with a 
        ValidationError and descriptive error message.
        """
        # Invalid emails should raise ValidationError
        with pytest.raises(ValidationError):
            validate_email(invalid_email)
