"""
Property-based tests for the validator module.

These tests verify universal properties across randomized inputs using hypothesis.
Each property test runs with a minimum of 100 iterations.
"""

import pytest
from hypothesis import given, settings, strategies as st
from hypothesis.strategies import emails
from user_registration.validator import (
    ValidationError,
    validate_email,
    validate_password_strength,
    validate_name,
)


class TestEmailValidationProperty:
    """Property-based tests for email validation."""
    
    @settings(max_examples=20)
    @given(email=emails())
    def test_valid_emails_are_accepted(self, email):
        """
        **Validates: Requirements 2.1, 2.2**
        Feature: user-registration-endpoint, Property 3: Email validation
        
        For any valid RFC 5322 format email, the validator should accept it.
        """
        # Valid emails generated by hypothesis should be accepted
        assert validate_email(email) is True
    
    @settings(max_examples=20)
    @given(
        invalid_email=st.one_of(
            # Email without @ symbol
            st.text(alphabet=st.characters(blacklist_characters='@'), min_size=1, max_size=50),
            # Just @ symbol
            st.just("@"),
            # @ at the start
            st.builds(lambda domain: f"@{domain}", domain=st.text(min_size=1, max_size=20)),
            # @ at the end
            st.builds(lambda local: f"{local}@", local=st.text(min_size=1, max_size=20)),
            # Multiple @ symbols
            st.builds(lambda a, b, c: f"{a}@{b}@{c}", 
                     a=st.text(min_size=1, max_size=10),
                     b=st.text(min_size=1, max_size=10),
                     c=st.text(min_size=1, max_size=10)),
            # Empty string
            st.just(""),
            # Whitespace only
            st.text(alphabet=" \t\n", min_size=1, max_size=10),
            # No domain after @
            st.builds(lambda local: f"{local}@", 
                     local=st.text(alphabet=st.characters(blacklist_characters='@'), 
                                  min_size=1, max_size=20)),
            # Invalid characters in domain
            st.builds(lambda local, domain: f"{local}@{domain}", 
                     local=st.text(alphabet=st.characters(blacklist_characters='@'), 
                                  min_size=1, max_size=20),
                     domain=st.text(alphabet="!#$%&*", min_size=1, max_size=10)),
        )
    )
    def test_invalid_emails_are_rejected(self, invalid_email):
        """
        **Validates: Requirements 2.1, 2.2**
        Feature: user-registration-endpoint, Property 3: Email validation
        
        For any invalid email format, the validator should reject it with a 
        ValidationError and descriptive error message.
        """
        # Invalid emails should raise ValidationError
        with pytest.raises(ValidationError):
            validate_email(invalid_email)


class TestPasswordStrengthValidationProperty:
    """Property-based tests for password strength validation."""
    
    @settings(max_examples=20)
    @given(
        password=st.builds(
            lambda upper, lower, digit, special, extra: upper + lower + digit + special + extra,
            upper=st.text(alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ', min_size=1, max_size=1),
            lower=st.text(alphabet='abcdefghijklmnopqrstuvwxyz', min_size=1, max_size=1),
            digit=st.text(alphabet='0123456789', min_size=1, max_size=1),
            special=st.text(alphabet='!@#$%^&*()_+-=[]{}|;:,.<>?', min_size=1, max_size=1),
            extra=st.text(alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*()_+-=[]{}|;:,.<>?', min_size=4, max_size=50)
        )
    )
    def test_valid_passwords_are_accepted(self, password):
        """
        **Validates: Requirements 2.3, 2.4, 2.5**
        Feature: user-registration-endpoint, Property 4: Password strength validation
        
        For any password string that meets all strength requirements (minimum 8 characters,
        at least one uppercase, one lowercase, one digit, one special character), the 
        validator should accept it.
        """
        # Valid passwords meeting all requirements should be accepted
        assert validate_password_strength(password) is True
    
    @settings(max_examples=20)
    @given(
        invalid_password=st.one_of(
            # Too short (less than 8 characters)
            st.text(alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*()_+-=[]{}|;:,.<>?', min_size=1, max_size=7),
            # Missing uppercase letter (8+ chars, has lower, digit, special)
            st.builds(
                lambda lower, digit, special, extra: lower + digit + special + extra,
                lower=st.text(alphabet='abcdefghijklmnopqrstuvwxyz', min_size=1, max_size=1),
                digit=st.text(alphabet='0123456789', min_size=1, max_size=1),
                special=st.text(alphabet='!@#$%^&*()_+-=[]{}|;:,.<>?', min_size=1, max_size=1),
                extra=st.text(alphabet='abcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*()_+-=[]{}|;:,.<>?', min_size=4, max_size=50)
            ),
            # Missing lowercase letter (8+ chars, has upper, digit, special)
            st.builds(
                lambda upper, digit, special, extra: upper + digit + special + extra,
                upper=st.text(alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ', min_size=1, max_size=1),
                digit=st.text(alphabet='0123456789', min_size=1, max_size=1),
                special=st.text(alphabet='!@#$%^&*()_+-=[]{}|;:,.<>?', min_size=1, max_size=1),
                extra=st.text(alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%^&*()_+-=[]{}|;:,.<>?', min_size=4, max_size=50)
            ),
            # Missing digit (8+ chars, has upper, lower, special)
            st.builds(
                lambda upper, lower, special, extra: upper + lower + special + extra,
                upper=st.text(alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ', min_size=1, max_size=1),
                lower=st.text(alphabet='abcdefghijklmnopqrstuvwxyz', min_size=1, max_size=1),
                special=st.text(alphabet='!@#$%^&*()_+-=[]{}|;:,.<>?', min_size=1, max_size=1),
                extra=st.text(alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz!@#$%^&*()_+-=[]{}|;:,.<>?', min_size=4, max_size=50)
            ),
            # Missing special character (8+ chars, has upper, lower, digit)
            st.builds(
                lambda upper, lower, digit, extra: upper + lower + digit + extra,
                upper=st.text(alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ', min_size=1, max_size=1),
                lower=st.text(alphabet='abcdefghijklmnopqrstuvwxyz', min_size=1, max_size=1),
                digit=st.text(alphabet='0123456789', min_size=1, max_size=1),
                extra=st.text(alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789', min_size=4, max_size=50)
            ),
            # Empty string
            st.just(""),
            # Only uppercase letters
            st.text(alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ', min_size=8, max_size=20),
            # Only lowercase letters
            st.text(alphabet='abcdefghijklmnopqrstuvwxyz', min_size=8, max_size=20),
            # Only digits
            st.text(alphabet='0123456789', min_size=8, max_size=20),
            # Only special characters
            st.text(alphabet='!@#$%^&*()_+-=[]{}|;:,.<>?', min_size=8, max_size=20),
        )
    )
    def test_invalid_passwords_are_rejected(self, invalid_password):
        """
        **Validates: Requirements 2.3, 2.4, 2.5**
        Feature: user-registration-endpoint, Property 4: Password strength validation
        
        For any password string that fails to meet strength requirements, the validator
        should reject it with a 400 status code and descriptive error message.
        """
        # Invalid passwords should raise ValidationError
        with pytest.raises(ValidationError):
            validate_password_strength(invalid_password)


class TestNameValidationProperty:
    """Property-based tests for name validation."""
    
    @settings(max_examples=20)
    @given(
        name=st.builds(
            lambda prefix, content, suffix: prefix + content + suffix,
            prefix=st.text(alphabet=' \t', min_size=0, max_size=5),
            content=st.text(
                alphabet=st.characters(blacklist_categories=['Cs', 'Cc'], blacklist_characters=' \t\n\r'),
                min_size=1,
                max_size=50
            ),
            suffix=st.text(alphabet=' \t', min_size=0, max_size=5)
        )
    )
    def test_valid_names_are_accepted(self, name):
        """
        **Validates: Requirements 2.6, 2.7**
        Feature: user-registration-endpoint, Property 5: Name validation
        
        For any name string that is non-empty after trimming whitespace, the 
        validator should accept it.
        """
        # Valid names (non-empty after trimming) should be accepted
        assert validate_name(name) is True
    
    @settings(max_examples=20)
    @given(
        invalid_name=st.one_of(
            # Empty string
            st.just(""),
            # Only spaces
            st.text(alphabet=' ', min_size=1, max_size=20),
            # Only tabs
            st.text(alphabet='\t', min_size=1, max_size=20),
            # Only newlines
            st.text(alphabet='\n', min_size=1, max_size=20),
            # Only carriage returns
            st.text(alphabet='\r', min_size=1, max_size=20),
            # Mix of whitespace characters
            st.text(alphabet=' \t\n\r', min_size=1, max_size=20),
        )
    )
    def test_invalid_names_are_rejected(self, invalid_name):
        """
        **Validates: Requirements 2.6, 2.7**
        Feature: user-registration-endpoint, Property 5: Name validation
        
        For any name string that is empty or only whitespace, the validator should 
        reject it with a 400 status code and descriptive error message.
        """
        # Invalid names (empty or whitespace-only) should raise ValidationError
        with pytest.raises(ValidationError):
            validate_name(invalid_name)
